<!DOCTYPE html>
<html>
    <head>
        <title>ShareAV</title>
        <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    </head>
    <body>
        <div id="page">
            <div id="header">
                <?php echo $this->partial('header.phtml')?>
            </div>
            <div id="leftpane">
                Just a mo...
            </div>
            <div id="content">
                <?php echo $this->layout()->content?>
            </div>
            <div id="rightpane">
            </div>
            <div id="footer">
                All content copywrong Dan Dart - All rights reversed.
            </div>
            </div>
    </body>
</html>
